spring.application.name=AstroReserva

# Conexion a la base de datos (Corregido puerto y nombre DB)
spring.datasource.url=jdbc:mysql://localhost:3306/astroreserva?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (Cambiado a update para mayor flexibilidad)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seguridad
logging.level.org.springframework.security=DEBUG