import {
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  importProvidersFrom,
} from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import {
  ArrowLeft,
  MapPin,
  Calendar,
  Clock,
  Users,
  Eye,
  Telescope,
  Timer,
  Search,
  Moon,
  ChevronRight,
  Home,
  User,
  Settings,
  Minus,
  Plus,
  LayoutDashboard,
  TrendingUp,
  DollarSign,
  Percent,
  Zap,
  Filter,
  MoreVertical,
  Camera,
  Sparkles,
  BookOpen,
  ArrowRight,
  Mail,
  Lock,
  FileText,
  CheckCircle,
  Edit,
  Trash,
  History,
  LucideAngularModule,
  ChevronLeft,
  XCircle,
  Ticket,
  CreditCard,
  Edit3,
  UserPlus,
} from 'lucide-angular';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './interceptors/auth.interceptor-interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowLeft,
        MapPin,
        Calendar,
        Clock,
        Users,
        Eye,
        Telescope,
        Timer,
        Search,
        Moon,
        ChevronRight,
        Home,
        User,
        Settings,
        Minus,
        Plus,
        LayoutDashboard,
        TrendingUp,
        DollarSign,
        Percent,
        Zap,
        Filter,
        MoreVertical,
        Camera,
        Sparkles,
        BookOpen,
        ArrowRight,
        Mail,
        Lock,
        FileText,
        CheckCircle,
        Edit,
        Trash,
        ChevronLeft,
        History,
        XCircle,
        Ticket,
        CreditCard,
        Edit3,
        UserPlus
      }),
    ),
    provideHttpClient(withInterceptors([authInterceptor])),
  ],
};
